theme = "onedark"

[editor]
rulers = [101]
cursorline = true

[editor.statusline]
right = [
  "diagnostics",
  "register",
  "separator",
  "file-type",
  "separator",
  "position-percentage",
  "position",
]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
separator = " ⟨ "

[editor.inline-diagnostics]
cursor-line = "hint"
